-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity exdes_v_tpg_0_v_tpg is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    fid_in : IN STD_LOGIC;
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    fid : OUT STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of exdes_v_tpg_0_v_tpg is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "exdes_v_tpg_0_v_tpg,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.378000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2924,HLS_SYN_LUT=6729,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv29_1 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal height : STD_LOGIC_VECTOR (15 downto 0);
    signal width : STD_LOGIC_VECTOR (15 downto 0);
    signal field_id : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartX : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartY : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruEndX : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruEndY : STD_LOGIC_VECTOR (15 downto 0);
    signal enableInput : STD_LOGIC_VECTOR (7 downto 0);
    signal bckgndId : STD_LOGIC_VECTOR (7 downto 0);
    signal ovrlayId : STD_LOGIC_VECTOR (7 downto 0);
    signal maskId : STD_LOGIC_VECTOR (7 downto 0);
    signal motionSpeed : STD_LOGIC_VECTOR (7 downto 0);
    signal colorFormat : STD_LOGIC_VECTOR (7 downto 0);
    signal crossHairX : STD_LOGIC_VECTOR (15 downto 0);
    signal crossHairY : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContStart : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContDelta : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateVerContStart : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateVerContDelta : STD_LOGIC_VECTOR (15 downto 0);
    signal boxSize : STD_LOGIC_VECTOR (15 downto 0);
    signal boxColorR : STD_LOGIC_VECTOR (15 downto 0);
    signal boxColorG : STD_LOGIC_VECTOR (15 downto 0);
    signal boxColorB : STD_LOGIC_VECTOR (15 downto 0);
    signal dpDynamicRange : STD_LOGIC_VECTOR (7 downto 0);
    signal dpYUVCoef : STD_LOGIC_VECTOR (7 downto 0);
    signal bck_motion_en : STD_LOGIC_VECTOR (15 downto 0);
    signal count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal s : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal icmp_ln455_fu_427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln455_reg_494 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln457_fu_437_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln457_reg_498 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_fid_in : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDATA : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TKEEP : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TSTRB : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_fid : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_s_axis_video_TREADY : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_ap_start : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TREADY : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_fid_ap_vld : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_ap_done : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_ap_ready : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_ap_idle : STD_LOGIC;
    signal grp_v_tpgHlsDataFlow_fu_287_ap_continue : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_421_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reg_unsigned_short_s_fu_421_ap_ce : STD_LOGIC;
    signal count_new_0_reg_276 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln458_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_tpgHlsDataFlow_fu_287_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_ready : STD_LOGIC;
    signal ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_done : STD_LOGIC;
    signal ap_block_state5_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done : STD_LOGIC := '0';
    signal select_ln460_fu_474_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_452_p4 : STD_LOGIC_VECTOR (28 downto 0);
    signal icmp_ln460_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln462_fu_468_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_m_axis_video_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDATA_int_regslice : STD_LOGIC_VECTOR (47 downto 0);
    signal s_axis_video_TVALID_int_regslice : STD_LOGIC;
    signal s_axis_video_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TKEEP_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_s_axis_video_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TSTRB_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_s_axis_video_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_ack_in : STD_LOGIC;
    signal m_axis_video_TVALID_int_regslice : STD_LOGIC;
    signal m_axis_video_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_m_axis_video_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component exdes_v_tpg_0_v_tpgHlsDataFlow IS
    port (
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (47 downto 0);
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (5 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        height : IN STD_LOGIC_VECTOR (15 downto 0);
        width : IN STD_LOGIC_VECTOR (15 downto 0);
        field_id : IN STD_LOGIC_VECTOR (15 downto 0);
        fid_in : IN STD_LOGIC_VECTOR (0 downto 0);
        passthruStartX : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndY : IN STD_LOGIC_VECTOR (15 downto 0);
        enableInput : IN STD_LOGIC_VECTOR (7 downto 0);
        bckgndId : IN STD_LOGIC_VECTOR (7 downto 0);
        motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
        colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        fid : OUT STD_LOGIC_VECTOR (0 downto 0);
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TREADY : OUT STD_LOGIC;
        enableInput_ap_vld : IN STD_LOGIC;
        height_ap_vld : IN STD_LOGIC;
        width_ap_vld : IN STD_LOGIC;
        colorFormat_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        passthruStartX_ap_vld : IN STD_LOGIC;
        passthruStartY_ap_vld : IN STD_LOGIC;
        passthruEndX_ap_vld : IN STD_LOGIC;
        passthruEndY_ap_vld : IN STD_LOGIC;
        bckgndId_ap_vld : IN STD_LOGIC;
        motionSpeed_ap_vld : IN STD_LOGIC;
        s_ap_vld : IN STD_LOGIC;
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        fid_in_ap_vld : IN STD_LOGIC;
        fid_ap_vld : OUT STD_LOGIC;
        field_id_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component exdes_v_tpg_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component exdes_v_tpg_0_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        height : OUT STD_LOGIC_VECTOR (15 downto 0);
        width : OUT STD_LOGIC_VECTOR (15 downto 0);
        bckgndId : OUT STD_LOGIC_VECTOR (7 downto 0);
        ovrlayId : OUT STD_LOGIC_VECTOR (7 downto 0);
        maskId : OUT STD_LOGIC_VECTOR (7 downto 0);
        motionSpeed : OUT STD_LOGIC_VECTOR (7 downto 0);
        colorFormat : OUT STD_LOGIC_VECTOR (7 downto 0);
        crossHairX : OUT STD_LOGIC_VECTOR (15 downto 0);
        crossHairY : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContStart : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContDelta : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxSize : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxColorR : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxColorG : OUT STD_LOGIC_VECTOR (15 downto 0);
        boxColorB : OUT STD_LOGIC_VECTOR (15 downto 0);
        enableInput : OUT STD_LOGIC_VECTOR (7 downto 0);
        passthruStartX : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruEndY : OUT STD_LOGIC_VECTOR (15 downto 0);
        dpDynamicRange : OUT STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef : OUT STD_LOGIC_VECTOR (7 downto 0);
        field_id : OUT STD_LOGIC_VECTOR (15 downto 0);
        bck_motion_en : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component exdes_v_tpg_0_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_v_tpgHlsDataFlow_fu_287 : component exdes_v_tpg_0_v_tpgHlsDataFlow
    port map (
        s_axis_video_TDATA => s_axis_video_TDATA_int_regslice,
        s_axis_video_TKEEP => s_axis_video_TKEEP_int_regslice,
        s_axis_video_TSTRB => s_axis_video_TSTRB_int_regslice,
        s_axis_video_TUSER => s_axis_video_TUSER_int_regslice,
        s_axis_video_TLAST => s_axis_video_TLAST_int_regslice,
        s_axis_video_TID => s_axis_video_TID_int_regslice,
        s_axis_video_TDEST => s_axis_video_TDEST_int_regslice,
        height => height,
        width => width,
        field_id => field_id,
        fid_in => grp_v_tpgHlsDataFlow_fu_287_fid_in,
        passthruStartX => passthruStartX,
        passthruStartY => passthruStartY,
        passthruEndX => passthruEndX,
        passthruEndY => passthruEndY,
        enableInput => enableInput,
        bckgndId => bckgndId,
        motionSpeed => motionSpeed,
        colorFormat => colorFormat,
        m_axis_video_TDATA => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDATA,
        m_axis_video_TKEEP => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TKEEP,
        m_axis_video_TSTRB => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TSTRB,
        m_axis_video_TUSER => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TUSER,
        m_axis_video_TLAST => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TLAST,
        m_axis_video_TID => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TID,
        m_axis_video_TDEST => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDEST,
        fid => grp_v_tpgHlsDataFlow_fu_287_fid,
        s => s,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        s_axis_video_TVALID => s_axis_video_TVALID_int_regslice,
        s_axis_video_TREADY => grp_v_tpgHlsDataFlow_fu_287_s_axis_video_TREADY,
        enableInput_ap_vld => ap_const_logic_1,
        height_ap_vld => ap_const_logic_1,
        width_ap_vld => ap_const_logic_1,
        colorFormat_ap_vld => ap_const_logic_1,
        ap_start => grp_v_tpgHlsDataFlow_fu_287_ap_start,
        passthruStartX_ap_vld => ap_const_logic_1,
        passthruStartY_ap_vld => ap_const_logic_1,
        passthruEndX_ap_vld => ap_const_logic_1,
        passthruEndY_ap_vld => ap_const_logic_1,
        bckgndId_ap_vld => ap_const_logic_1,
        motionSpeed_ap_vld => ap_const_logic_1,
        s_ap_vld => ap_const_logic_1,
        m_axis_video_TVALID => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        m_axis_video_TREADY => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TREADY,
        fid_in_ap_vld => ap_const_logic_1,
        fid_ap_vld => grp_v_tpgHlsDataFlow_fu_287_fid_ap_vld,
        field_id_ap_vld => ap_const_logic_1,
        ap_done => grp_v_tpgHlsDataFlow_fu_287_ap_done,
        ap_ready => grp_v_tpgHlsDataFlow_fu_287_ap_ready,
        ap_idle => grp_v_tpgHlsDataFlow_fu_287_ap_idle,
        ap_continue => grp_v_tpgHlsDataFlow_fu_287_ap_continue);

    grp_reg_unsigned_short_s_fu_421 : component exdes_v_tpg_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        d => bck_motion_en,
        ap_return => grp_reg_unsigned_short_s_fu_421_ap_return,
        ap_ce => grp_reg_unsigned_short_s_fu_421_ap_ce);

    CTRL_s_axi_U : component exdes_v_tpg_0_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        height => height,
        width => width,
        bckgndId => bckgndId,
        ovrlayId => ovrlayId,
        maskId => maskId,
        motionSpeed => motionSpeed,
        colorFormat => colorFormat,
        crossHairX => crossHairX,
        crossHairY => crossHairY,
        ZplateHorContStart => ZplateHorContStart,
        ZplateHorContDelta => ZplateHorContDelta,
        ZplateVerContStart => ZplateVerContStart,
        ZplateVerContDelta => ZplateVerContDelta,
        boxSize => boxSize,
        boxColorR => boxColorR,
        boxColorG => boxColorG,
        boxColorB => boxColorB,
        enableInput => enableInput,
        passthruStartX => passthruStartX,
        passthruStartY => passthruStartY,
        passthruEndX => passthruEndX,
        passthruEndY => passthruEndY,
        dpDynamicRange => dpDynamicRange,
        dpYUVCoef => dpYUVCoef,
        field_id => field_id,
        bck_motion_en => bck_motion_en,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    regslice_both_s_axis_video_V_data_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 48)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TDATA,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_data_V_U_ack_in,
        data_out => s_axis_video_TDATA_int_regslice,
        vld_out => s_axis_video_TVALID_int_regslice,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_data_V_U_apdone_blk);

    regslice_both_s_axis_video_V_keep_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TKEEP,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_keep_V_U_ack_in,
        data_out => s_axis_video_TKEEP_int_regslice,
        vld_out => regslice_both_s_axis_video_V_keep_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_video_V_strb_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TSTRB,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_strb_V_U_ack_in,
        data_out => s_axis_video_TSTRB_int_regslice,
        vld_out => regslice_both_s_axis_video_V_strb_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_video_V_user_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TUSER,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_user_V_U_ack_in,
        data_out => s_axis_video_TUSER_int_regslice,
        vld_out => regslice_both_s_axis_video_V_user_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_user_V_U_apdone_blk);

    regslice_both_s_axis_video_V_last_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TLAST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_last_V_U_ack_in,
        data_out => s_axis_video_TLAST_int_regslice,
        vld_out => regslice_both_s_axis_video_V_last_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_last_V_U_apdone_blk);

    regslice_both_s_axis_video_V_id_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TID,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_id_V_U_ack_in,
        data_out => s_axis_video_TID_int_regslice,
        vld_out => regslice_both_s_axis_video_V_id_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_id_V_U_apdone_blk);

    regslice_both_s_axis_video_V_dest_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TDEST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_dest_V_U_ack_in,
        data_out => s_axis_video_TDEST_int_regslice,
        vld_out => regslice_both_s_axis_video_V_dest_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int_regslice,
        apdone_blk => regslice_both_s_axis_video_V_dest_V_U_apdone_blk);

    regslice_both_m_axis_video_V_data_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 48)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDATA,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => m_axis_video_TREADY_int_regslice,
        data_out => m_axis_video_TDATA,
        vld_out => regslice_both_m_axis_video_V_data_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_data_V_U_apdone_blk);

    regslice_both_m_axis_video_V_keep_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TKEEP,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_video_TKEEP,
        vld_out => regslice_both_m_axis_video_V_keep_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_video_V_strb_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TSTRB,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_video_TSTRB,
        vld_out => regslice_both_m_axis_video_V_strb_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_video_V_user_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TUSER,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_user_V_U_ack_in_dummy,
        data_out => m_axis_video_TUSER,
        vld_out => regslice_both_m_axis_video_V_user_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_user_V_U_apdone_blk);

    regslice_both_m_axis_video_V_last_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TLAST,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_last_V_U_ack_in_dummy,
        data_out => m_axis_video_TLAST,
        vld_out => regslice_both_m_axis_video_V_last_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_last_V_U_apdone_blk);

    regslice_both_m_axis_video_V_id_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TID,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_id_V_U_ack_in_dummy,
        data_out => m_axis_video_TID,
        vld_out => regslice_both_m_axis_video_V_id_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_id_V_U_apdone_blk);

    regslice_both_m_axis_video_V_dest_V_U : component exdes_v_tpg_0_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TDEST,
        vld_in => grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID,
        ack_in => regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy,
        data_out => m_axis_video_TDEST,
        vld_out => regslice_both_m_axis_video_V_dest_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done <= ap_const_logic_0;
                elsif ((grp_v_tpgHlsDataFlow_fu_287_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready <= ap_const_logic_0;
                elsif ((grp_v_tpgHlsDataFlow_fu_287_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_tpgHlsDataFlow_fu_287_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_v_tpgHlsDataFlow_fu_287_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5)))) then 
                    grp_v_tpgHlsDataFlow_fu_287_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_tpgHlsDataFlow_fu_287_ap_ready = ap_const_logic_1)) then 
                    grp_v_tpgHlsDataFlow_fu_287_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_new_0_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((icmp_ln458_fu_443_p2 = ap_const_lv1_0)) then 
                    count_new_0_reg_276 <= add_ln457_reg_498;
                elsif ((icmp_ln458_fu_443_p2 = ap_const_lv1_1)) then 
                    count_new_0_reg_276 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln455_fu_427_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln457_reg_498 <= add_ln457_fu_437_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln455_reg_494 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                count <= count_new_0_reg_276;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln455_reg_494 <= icmp_ln455_fu_427_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln458_fu_443_p2 = ap_const_lv1_1))) then
                s <= select_ln460_fu_474_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln455_fu_427_p2, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state5_on_subcall_done, ap_CS_fsm_state6, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln455_fu_427_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln457_fu_437_p2 <= std_logic_vector(unsigned(count) + unsigned(ap_const_lv32_1));
    add_ln462_fu_468_p2 <= std_logic_vector(unsigned(s) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state5_on_subcall_done)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state5_on_subcall_done_assign_proc : process(ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_ready, ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_done)
    begin
                ap_block_state5_on_subcall_done <= ((ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_ready and ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_done) = ap_const_logic_0);
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_done <= (grp_v_tpgHlsDataFlow_fu_287_ap_done or ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_done);
    ap_sync_grp_v_tpgHlsDataFlow_fu_287_ap_ready <= (grp_v_tpgHlsDataFlow_fu_287_ap_ready or ap_sync_reg_grp_v_tpgHlsDataFlow_fu_287_ap_ready);
    fid <= grp_v_tpgHlsDataFlow_fu_287_fid(0);

    grp_reg_unsigned_short_s_fu_421_ap_ce_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            grp_reg_unsigned_short_s_fu_421_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_421_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_v_tpgHlsDataFlow_fu_287_ap_continue_assign_proc : process(ap_CS_fsm_state5, ap_block_state5_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state5_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            grp_v_tpgHlsDataFlow_fu_287_ap_continue <= ap_const_logic_1;
        else 
            grp_v_tpgHlsDataFlow_fu_287_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_v_tpgHlsDataFlow_fu_287_ap_start <= grp_v_tpgHlsDataFlow_fu_287_ap_start_reg;
    grp_v_tpgHlsDataFlow_fu_287_fid_in <= (0=>fid_in, others=>'-');
    grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TREADY <= (m_axis_video_TREADY_int_regslice and ap_CS_fsm_state5);
    icmp_ln455_fu_427_p2 <= "1" when (grp_reg_unsigned_short_s_fu_421_ap_return = ap_const_lv16_1) else "0";
    icmp_ln458_fu_443_p2 <= "1" when (add_ln457_reg_498 = ap_const_lv32_A) else "0";
    icmp_ln460_fu_462_p2 <= "1" when (signed(tmp_1_fu_452_p4) < signed(ap_const_lv29_1)) else "0";
    m_axis_video_TVALID <= regslice_both_m_axis_video_V_data_V_U_vld_out;
    m_axis_video_TVALID_int_regslice <= grp_v_tpgHlsDataFlow_fu_287_m_axis_video_TVALID;
    s_axis_video_TREADY <= regslice_both_s_axis_video_V_data_V_U_ack_in;

    s_axis_video_TREADY_int_regslice_assign_proc : process(grp_v_tpgHlsDataFlow_fu_287_s_axis_video_TREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_axis_video_TREADY_int_regslice <= grp_v_tpgHlsDataFlow_fu_287_s_axis_video_TREADY;
        else 
            s_axis_video_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln460_fu_474_p3 <= 
        add_ln462_fu_468_p2 when (icmp_ln460_fu_462_p2(0) = '1') else 
        ap_const_lv32_0;
    tmp_1_fu_452_p4 <= s(31 downto 3);
end behav;
