-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity exdes_v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sof : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    div283_cast : IN STD_LOGIC_VECTOR (11 downto 0);
    fid_in_load : IN STD_LOGIC_VECTOR (0 downto 0);
    fid : OUT STD_LOGIC_VECTOR (0 downto 0);
    fid_ap_vld : OUT STD_LOGIC;
    ovrlayYUV_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_empty_n : IN STD_LOGIC;
    ovrlayYUV_read : OUT STD_LOGIC;
    icmp_ln975_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln975 : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    field_id_load : IN STD_LOGIC_VECTOR (15 downto 0);
    sub_cast : IN STD_LOGIC_VECTOR (11 downto 0);
    counter_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
    counter_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    counter_loc_1_out_o_ap_vld : OUT STD_LOGIC;
    p_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_phi_out_ap_vld : OUT STD_LOGIC;
    counter : OUT STD_LOGIC_VECTOR (15 downto 0);
    counter_ap_vld : OUT STD_LOGIC );
end;


architecture behav of exdes_v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv16_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln936_reg_584 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TDATA_blk_n : STD_LOGIC;
    signal tmp_user_V_reg_232 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_phi_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal field_id_load_read_read_fu_146_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_cast_cast_fu_275_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_cast_cast_reg_579 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln936_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_last_V_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_588 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_phi_mux_tmp_user_V_phi_fu_236_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_144_phi_fu_260_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter0_empty_144_reg_254 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp0_iter1_empty_144_reg_254 : STD_LOGIC_VECTOR (0 downto 0);
    signal fid_toggle_fu_338_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal fid_toggle_1_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln960_fu_311_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal j_fu_136 : STD_LOGIC_VECTOR (11 downto 0);
    signal j_2_fu_296_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln936_fu_287_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal pix_444_V_fu_344_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_rgb_V_4_fu_368_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_1_fu_406_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Result_s_fu_398_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal axi_data_V_fu_414_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pix_rgb_V_5_fu_378_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_422_V_fu_388_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_1_fu_432_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_rgb_V_fu_348_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_3_fu_446_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_rgb_V_6_fu_358_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_5_fu_460_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_7_fu_474_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_8_fu_481_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_6_fu_467_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_4_fu_453_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_2_fu_439_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln975_fu_425_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln880_fu_421_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_s_fu_488_p6 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_165 : BOOLEAN;
    signal ap_condition_142 : BOOLEAN;
    signal ap_condition_389 : BOOLEAN;
    signal ap_condition_392 : BOOLEAN;
    signal ap_condition_395 : BOOLEAN;
    signal ap_condition_398 : BOOLEAN;
    signal ap_condition_401 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_empty_144_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_142)) then
                if ((ap_const_boolean_1 = ap_condition_165)) then 
                    ap_phi_reg_pp0_iter1_empty_144_reg_254 <= fid_in_load;
                elsif (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_2))) then 
                    ap_phi_reg_pp0_iter1_empty_144_reg_254 <= ap_const_lv1_1;
                elsif (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_0))) then 
                    ap_phi_reg_pp0_iter1_empty_144_reg_254 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_empty_144_reg_254 <= ap_phi_reg_pp0_iter0_empty_144_reg_254;
                end if;
            end if; 
        end if;
    end process;

    j_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_fu_136 <= ap_const_lv12_0;
            elsif (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                j_fu_136 <= j_2_fu_296_p2;
            end if; 
        end if;
    end process;

    p_phi_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_phi_reg_244 <= empty;
            elsif (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_phi_reg_244 <= ap_phi_mux_empty_144_phi_fu_260_p10;
            end if; 
        end if;
    end process;

    tmp_user_V_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                tmp_user_V_reg_232 <= sof;
            elsif (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                tmp_user_V_reg_232 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln936_reg_584 <= icmp_ln936_fu_291_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sub_cast_cast_reg_579 <= sub_cast_cast_fu_275_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_last_V_reg_588 <= tmp_last_V_fu_302_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln936_fu_291_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln936_fu_291_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln936_fu_291_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln960_fu_311_p2 <= std_logic_vector(unsigned(counter_loc_1_out_i) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ovrlayYUV_empty_n, m_axis_video_TREADY, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ovrlayYUV_empty_n = ap_const_logic_0)) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ovrlayYUV_empty_n, m_axis_video_TREADY, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (ovrlayYUV_empty_n = ap_const_logic_0)) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ovrlayYUV_empty_n, m_axis_video_TREADY, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (ovrlayYUV_empty_n = ap_const_logic_0)) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0))));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(m_axis_video_TREADY, icmp_ln936_reg_584)
    begin
                ap_block_state3_io <= ((icmp_ln936_reg_584 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(ovrlayYUV_empty_n, m_axis_video_TREADY, icmp_ln936_reg_584)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ovrlayYUV_empty_n = ap_const_logic_0)) or ((icmp_ln936_reg_584 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0)));
    end process;


    ap_condition_142_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_142 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_165_assign_proc : process(field_id_load_read_read_fu_146_p2, icmp_ln936_fu_291_p2)
    begin
                ap_condition_165 <= (not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_2)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_0)) and (icmp_ln936_fu_291_p2 = ap_const_lv1_0));
    end process;


    ap_condition_389_assign_proc : process(field_id_load_read_read_fu_146_p2, icmp_ln936_fu_291_p2, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_389 <= ((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_392_assign_proc : process(field_id_load_read_read_fu_146_p2, icmp_ln936_fu_291_p2, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_392 <= ((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_395_assign_proc : process(field_id_load_read_read_fu_146_p2, icmp_ln936_fu_291_p2, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_395 <= (not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_2)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_0)) and (icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_398_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, field_id_load_read_read_fu_146_p2)
    begin
                ap_condition_398 <= ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3) and (icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_401_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, field_id_load_read_read_fu_146_p2)
    begin
                ap_condition_401 <= ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1) and (icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln936_fu_291_p2)
    begin
        if ((icmp_ln936_fu_291_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_144_phi_fu_260_p10_assign_proc : process(icmp_ln936_reg_584, field_id_load_read_read_fu_146_p2, ap_phi_reg_pp0_iter1_empty_144_reg_254, fid_toggle_fu_338_p1, fid_toggle_1_fu_515_p2)
    begin
        if ((icmp_ln936_reg_584 = ap_const_lv1_0)) then
            if ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3)) then 
                ap_phi_mux_empty_144_phi_fu_260_p10 <= fid_toggle_1_fu_515_p2;
            elsif ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1)) then 
                ap_phi_mux_empty_144_phi_fu_260_p10 <= fid_toggle_fu_338_p1;
            else 
                ap_phi_mux_empty_144_phi_fu_260_p10 <= ap_phi_reg_pp0_iter1_empty_144_reg_254;
            end if;
        else 
            ap_phi_mux_empty_144_phi_fu_260_p10 <= ap_phi_reg_pp0_iter1_empty_144_reg_254;
        end if; 
    end process;


    ap_phi_mux_tmp_user_V_phi_fu_236_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln936_reg_584, tmp_user_V_reg_232)
    begin
        if (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_tmp_user_V_phi_fu_236_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_tmp_user_V_phi_fu_236_p4 <= tmp_user_V_reg_232;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_empty_144_reg_254 <= "X";

    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axi_data_V_fu_414_p3 <= 
        p_Result_1_fu_406_p3 when (icmp_ln975_1(0) = '1') else 
        p_Result_s_fu_398_p3;
    counter <= std_logic_vector(unsigned(counter_loc_1_out_i) + unsigned(ap_const_lv16_1));

    counter_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln936_fu_291_p2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_phi_mux_tmp_user_V_phi_fu_236_p4)
    begin
        if (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tmp_user_V_phi_fu_236_p4 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            counter_ap_vld <= ap_const_logic_1;
        else 
            counter_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    counter_loc_1_out_o_assign_proc : process(counter_loc_1_out_i, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, icmp_ln936_fu_291_p2, ap_enable_reg_pp0_iter0, ap_phi_mux_tmp_user_V_phi_fu_236_p4, add_ln960_fu_311_p2)
    begin
        if (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tmp_user_V_phi_fu_236_p4 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            counter_loc_1_out_o <= add_ln960_fu_311_p2;
        else 
            counter_loc_1_out_o <= counter_loc_1_out_i;
        end if; 
    end process;


    counter_loc_1_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln936_fu_291_p2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_phi_mux_tmp_user_V_phi_fu_236_p4)
    begin
        if (((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_tmp_user_V_phi_fu_236_p4 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            counter_loc_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            counter_loc_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    fid_assign_proc : process(fid_in_load, ap_CS_fsm_pp0_stage0, fid_toggle_fu_338_p1, fid_toggle_1_fu_515_p2, ap_block_pp0_stage0_01001, ap_condition_389, ap_condition_392, ap_condition_395, ap_condition_398, ap_condition_401)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_const_boolean_1 = ap_condition_401)) then 
                fid <= fid_toggle_fu_338_p1;
            elsif ((ap_const_boolean_1 = ap_condition_398)) then 
                fid <= fid_toggle_1_fu_515_p2;
            elsif ((ap_const_boolean_1 = ap_condition_395)) then 
                fid <= fid_in_load;
            elsif ((ap_const_boolean_1 = ap_condition_392)) then 
                fid <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_389)) then 
                fid <= ap_const_lv1_1;
            else 
                fid <= "X";
            end if;
        else 
            fid <= "X";
        end if; 
    end process;


    fid_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, field_id_load_read_read_fu_146_p2, icmp_ln936_fu_291_p2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_2)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1)) and not((field_id_load_read_read_fu_146_p2 = ap_const_lv16_0)) and (icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_3) and (icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((field_id_load_read_read_fu_146_p2 = ap_const_lv16_1) and (icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_2) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((icmp_ln936_fu_291_p2 = ap_const_lv1_0) and (field_id_load_read_read_fu_146_p2 = ap_const_lv16_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
            fid_ap_vld <= ap_const_logic_1;
        else 
            fid_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    fid_toggle_1_fu_515_p2 <= (fid_toggle_fu_338_p1 xor ap_const_lv1_1);
    fid_toggle_fu_338_p1 <= counter_loc_1_out_i(1 - 1 downto 0);
    field_id_load_read_read_fu_146_p2 <= field_id_load;
    icmp_ln936_fu_291_p2 <= "1" when (j_fu_136 = div283_cast) else "0";
    j_2_fu_296_p2 <= std_logic_vector(unsigned(j_fu_136) + unsigned(ap_const_lv12_1));
    m_axis_video_TDATA <= (tmp_s_fu_488_p6 & sext_ln880_fu_421_p1(7 downto 0));

    m_axis_video_TDATA_blk_n_assign_proc : process(m_axis_video_TREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln936_reg_584)
    begin
        if (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_TDATA_blk_n <= m_axis_video_TREADY;
        else 
            m_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_video_TDEST <= ap_const_lv1_0;
    m_axis_video_TID <= ap_const_lv1_0;
    m_axis_video_TKEEP <= ap_const_lv6_3F;
    m_axis_video_TLAST <= tmp_last_V_reg_588;
    m_axis_video_TSTRB <= ap_const_lv6_0;
    m_axis_video_TUSER <= tmp_user_V_reg_232;

    m_axis_video_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_TVALID <= ap_const_logic_1;
        else 
            m_axis_video_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    ovrlayYUV_blk_n_assign_proc : process(ovrlayYUV_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln936_reg_584)
    begin
        if (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_empty_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ovrlayYUV_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln936_reg_584, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln936_reg_584 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ovrlayYUV_read <= ap_const_logic_1;
        else 
            ovrlayYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_1_fu_406_p3 <= (ap_const_lv1_1 & pix_rgb_V_4_fu_368_p4);
    p_Result_s_fu_398_p3 <= (ap_const_lv1_1 & pix_444_V_fu_344_p1);
    p_phi_out <= p_phi_reg_244;

    p_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            p_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_422_V_fu_388_p4 <= ovrlayYUV_dout(31 downto 24);
    pix_444_V_fu_344_p1 <= ovrlayYUV_dout(8 - 1 downto 0);
    pix_rgb_V_4_fu_368_p4 <= ovrlayYUV_dout(15 downto 8);
    pix_rgb_V_5_fu_378_p4 <= ovrlayYUV_dout(23 downto 16);
    pix_rgb_V_6_fu_358_p4 <= ovrlayYUV_dout(47 downto 40);
    pix_rgb_V_fu_348_p4 <= ovrlayYUV_dout(39 downto 32);
    select_ln975_1_fu_432_p3 <= 
        pix_rgb_V_5_fu_378_p4 when (icmp_ln975(0) = '1') else 
        pix_422_V_fu_388_p4;
    select_ln975_2_fu_439_p3 <= 
        pix_444_V_fu_344_p1 when (icmp_ln975_1(0) = '1') else 
        select_ln975_1_fu_432_p3;
    select_ln975_3_fu_446_p3 <= 
        pix_422_V_fu_388_p4 when (icmp_ln975(0) = '1') else 
        pix_rgb_V_fu_348_p4;
    select_ln975_4_fu_453_p3 <= 
        pix_rgb_V_fu_348_p4 when (icmp_ln975_1(0) = '1') else 
        select_ln975_3_fu_446_p3;
    select_ln975_5_fu_460_p3 <= 
        pix_rgb_V_fu_348_p4 when (icmp_ln975(0) = '1') else 
        pix_rgb_V_6_fu_358_p4;
    select_ln975_6_fu_467_p3 <= 
        pix_rgb_V_6_fu_358_p4 when (icmp_ln975_1(0) = '1') else 
        select_ln975_5_fu_460_p3;
    select_ln975_7_fu_474_p3 <= 
        pix_rgb_V_6_fu_358_p4 when (icmp_ln975(0) = '1') else 
        pix_rgb_V_5_fu_378_p4;
    select_ln975_8_fu_481_p3 <= 
        pix_422_V_fu_388_p4 when (icmp_ln975_1(0) = '1') else 
        select_ln975_7_fu_474_p3;
    select_ln975_fu_425_p3 <= 
        pix_rgb_V_5_fu_378_p4 when (icmp_ln975_1(0) = '1') else 
        pix_rgb_V_4_fu_368_p4;
        sext_ln880_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(axi_data_V_fu_414_p3),48));

        sub_cast_cast_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_cast),13));

    tmp_last_V_fu_302_p2 <= "1" when (zext_ln936_fu_287_p1 = sub_cast_cast_reg_579) else "0";
    tmp_s_fu_488_p6 <= ((((select_ln975_8_fu_481_p3 & select_ln975_6_fu_467_p3) & select_ln975_4_fu_453_p3) & select_ln975_2_fu_439_p3) & select_ln975_fu_425_p3);
    zext_ln936_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_136),13));
end behav;
