// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module exdes_v_tpg_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ovrlayYUV_dout,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        height,
        width,
        colorFormat,
        fid_in,
        fid,
        fid_ap_vld,
        field_id
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] ovrlayYUV_dout;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
output  [47:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [15:0] height;
input  [15:0] width;
input  [7:0] colorFormat;
input  [0:0] fid_in;
output  [0:0] fid;
output   fid_ap_vld;
input  [15:0] field_id;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg[0:0] fid;
reg fid_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] fidStored;
reg   [15:0] counter;
wire   [11:0] trunc_ln882_fu_186_p1;
reg   [11:0] trunc_ln882_reg_313;
wire   [11:0] div283_cast_fu_195_p4;
reg   [11:0] div283_cast_reg_318;
wire   [11:0] sub_fu_205_p2;
reg   [11:0] sub_reg_323;
wire   [0:0] cmp33265_fu_211_p2;
reg   [0:0] cmp33265_reg_338;
wire   [0:0] icmp_ln975_fu_221_p2;
reg   [0:0] icmp_ln975_reg_342;
wire   [0:0] icmp_ln975_1_fu_227_p2;
reg   [0:0] icmp_ln975_1_reg_347;
wire   [11:0] i_2_fu_261_p2;
reg   [11:0] i_2_reg_355;
wire    ap_CS_fsm_state2;
reg   [0:0] p_load_reg_360;
wire   [0:0] icmp_ln934_fu_256_p2;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_done;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_idle;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_ready;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid_ap_vld;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ovrlayYUV_read;
wire   [47:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDATA;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TVALID;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TREADY;
wire   [5:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TKEEP;
wire   [5:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TSTRB;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TUSER;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TLAST;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TID;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDEST;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o_ap_vld;
wire   [0:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out_ap_vld;
wire   [15:0] grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter;
wire    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_ap_vld;
reg    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [15:0] counter_loc_0_fu_108;
reg   [0:0] empty_fu_104;
reg   [11:0] i_fu_96;
reg    ap_block_state4_on_subcall_done;
reg    ap_block_state1;
reg   [0:0] sof_fu_100;
reg   [0:0] fid_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 fidStored = 1'd0;
#0 counter = 16'd0;
#0 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg = 1'b0;
#0 fid_preg = 1'd0;
end

exdes_v_tpg_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2 grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start),
    .ap_done(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_done),
    .ap_idle(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_idle),
    .ap_ready(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_ready),
    .sof(sof_fu_100),
    .empty(p_load_reg_360),
    .div283_cast(div283_cast_reg_318),
    .fid_in_load(fid_in),
    .fid(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid),
    .fid_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid_ap_vld),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_num_data_valid(5'd0),
    .ovrlayYUV_fifo_cap(5'd0),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ovrlayYUV_read),
    .icmp_ln975_1(icmp_ln975_1_reg_347),
    .icmp_ln975(icmp_ln975_reg_342),
    .m_axis_video_TDATA(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDATA),
    .m_axis_video_TVALID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TREADY),
    .m_axis_video_TKEEP(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TLAST),
    .m_axis_video_TID(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TID),
    .m_axis_video_TDEST(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDEST),
    .field_id_load(field_id),
    .sub_cast(sub_reg_323),
    .counter_loc_1_out_i(counter_loc_0_fu_108),
    .counter_loc_1_out_o(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o),
    .counter_loc_1_out_o_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o_ap_vld),
    .p_phi_out(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out),
    .p_phi_out_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out_ap_vld),
    .counter(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter),
    .counter_ap_vld(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln934_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        fid_preg <= 1'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            fid_preg <= fidStored;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_ready == 1'b1)) begin
            grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        counter_loc_0_fu_108 <= counter;
    end else if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o_ap_vld == 1'b1))) begin
        counter_loc_0_fu_108 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        empty_fu_104 <= fidStored;
    end else if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out_ap_vld == 1'b1))) begin
        empty_fu_104 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_p_phi_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_96 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
        i_fu_96 <= i_2_reg_355;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_100 <= 1'd1;
    end else if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
        sof_fu_100 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp33265_reg_338 <= cmp33265_fu_211_p2;
        div283_cast_reg_318 <= {{width[12:1]}};
        icmp_ln975_1_reg_347 <= icmp_ln975_1_fu_227_p2;
        icmp_ln975_reg_342 <= icmp_ln975_fu_221_p2;
        sub_reg_323 <= sub_fu_205_p2;
        trunc_ln882_reg_313 <= trunc_ln882_fu_186_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4) & (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter_ap_vld == 1'b1))) begin
        counter <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_counter;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln934_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        fidStored <= empty_fu_104;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_2_reg_355 <= i_2_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln934_fu_256_p2 == 1'd0) & (cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_load_reg_360 <= empty_fu_104;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln934_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln934_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fid = fidStored;
    end else if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid_ap_vld == 1'b1) & (cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        fid = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid;
    end else begin
        fid = fid_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        fid_ap_vld = 1'b1;
    end else if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        fid_ap_vld = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_fid_ap_vld;
    end else begin
        fid_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((cmp33265_reg_338 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ovrlayYUV_read = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ovrlayYUV_read;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln934_fu_256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln934_fu_256_p2 == 1'd0) & (cmp33265_reg_338 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_done == 1'b0) & (cmp33265_reg_338 == 1'd0));
end

assign cmp33265_fu_211_p2 = ((div283_cast_fu_195_p4 == 12'd0) ? 1'b1 : 1'b0);

assign div283_cast_fu_195_p4 = {{width[12:1]}};

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_ap_start_reg;

assign grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TREADY = (m_axis_video_TREADY & ap_CS_fsm_state4);

assign i_2_fu_261_p2 = (i_fu_96 + 12'd1);

assign icmp_ln934_fu_256_p2 = ((i_fu_96 == trunc_ln882_reg_313) ? 1'b1 : 1'b0);

assign icmp_ln975_1_fu_227_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln975_fu_221_p2 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign m_axis_video_TDATA = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDATA;

assign m_axis_video_TDEST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TDEST;

assign m_axis_video_TID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TID;

assign m_axis_video_TKEEP = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TKEEP;

assign m_axis_video_TLAST = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TLAST;

assign m_axis_video_TSTRB = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TSTRB;

assign m_axis_video_TUSER = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TUSER;

assign m_axis_video_TVALID = grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_936_2_fu_149_m_axis_video_TVALID;

assign sub_fu_205_p2 = ($signed(div283_cast_fu_195_p4) + $signed(12'd4095));

assign trunc_ln882_fu_186_p1 = height[11:0];

endmodule //exdes_v_tpg_0_MultiPixStream2AXIvideo
