# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0.xci
# IP: The module: 'exdes_v_hdmi_tx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/bd_3ea7.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7 || ORIG_REF_NAME==bd_3ea7} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_0/bd_3ea7_v_hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_hdmi_tx_0 || ORIG_REF_NAME==bd_3ea7_v_hdmi_tx_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_1/bd_3ea7_v_tc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_tc_0 || ORIG_REF_NAME==bd_3ea7_v_tc_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_2/bd_3ea7_v_axi4s_vid_out_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_3ea7_v_axi4s_vid_out_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_3/bd_3ea7_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_3ea7_util_vector_logic_0_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_3ea7_axi_crossbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_axi_crossbar_0 || ORIG_REF_NAME==bd_3ea7_axi_crossbar_0} -quiet] -quiet

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/bd_3ea7_ooc.xdc

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_v_hdmi_tx_ss_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.srcs/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0.xci
# IP: The module: 'exdes_v_hdmi_tx_ss_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/bd_3ea7.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7 || ORIG_REF_NAME==bd_3ea7} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_0/bd_3ea7_v_hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_hdmi_tx_0 || ORIG_REF_NAME==bd_3ea7_v_hdmi_tx_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_1/bd_3ea7_v_tc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_tc_0 || ORIG_REF_NAME==bd_3ea7_v_tc_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_2/bd_3ea7_v_axi4s_vid_out_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_3ea7_v_axi4s_vid_out_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_3/bd_3ea7_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_util_vector_logic_0_0 || ORIG_REF_NAME==bd_3ea7_util_vector_logic_0_0} -quiet] -quiet

# IP: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/ip/ip_4/bd_3ea7_axi_crossbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3ea7_axi_crossbar_0 || ORIG_REF_NAME==bd_3ea7_axi_crossbar_0} -quiet] -quiet

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/bd_0/bd_3ea7_ooc.xdc

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_v_hdmi_tx_ss_0/exdes_v_hdmi_tx_ss_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_v_hdmi_tx_ss_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
