# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.srcs/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0.xci
# IP: The module: 'exdes_hdmi_acr_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes/rtl/hdmi_acr_ctrl/hdmi_acr_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_hdmi_acr_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_hdmi_acr_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.srcs/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0.xci
# IP: The module: 'exdes_hdmi_acr_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes/rtl/hdmi_acr_ctrl/hdmi_acr_ctrl.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_hdmi_acr_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/xilinx_axi/v_dma_txss/v_hdmi_tx_ss_ex/v_hdmi_tx_ss_ex.gen/sources_1/bd/exdes/ip/exdes_hdmi_acr_ctrl_0/exdes_hdmi_acr_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'exdes_hdmi_acr_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
