// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module exdes_v_tpg_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        srcYUV_dout,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        srcYUV_empty_n,
        srcYUV_read,
        height,
        width,
        passthruStartX,
        passthruStartY,
        passthruEndX,
        passthruEndY,
        enableInput,
        bckgndId,
        motionSpeed,
        colorFormat,
        ovrlayYUV_din,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_full_n,
        ovrlayYUV_write,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] srcYUV_dout;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input   srcYUV_empty_n;
output   srcYUV_read;
input  [15:0] height;
input  [15:0] width;
input  [15:0] passthruStartX;
input  [15:0] passthruStartY;
input  [15:0] passthruEndX;
input  [15:0] passthruEndY;
input  [7:0] enableInput;
input  [7:0] bckgndId;
input  [7:0] motionSpeed;
input  [7:0] colorFormat;
output  [47:0] ovrlayYUV_din;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcYUV_read;
reg ovrlayYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [1:0] blkYuv_address0;
reg    blkYuv_ce0;
wire   [7:0] blkYuv_q0;
wire   [1:0] whiYuv_address0;
reg    whiYuv_ce0;
wire   [7:0] whiYuv_q0;
wire   [1:0] blkYuv_1_address0;
reg    blkYuv_1_ce0;
wire   [7:0] blkYuv_1_q0;
reg   [7:0] hBarSel_0_1;
reg   [7:0] hBarSel_1_1;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel_0;
reg   [2:0] hBarSel_1;
reg   [7:0] vBarSel_1;
reg   [2:0] hBarSel_0_2;
reg   [2:0] hBarSel_1_2;
reg   [7:0] rampStart;
wire   [0:0] icmp_fu_488_p2;
reg   [0:0] icmp_reg_952;
wire   [0:0] cmp4_i276_fu_494_p2;
reg   [0:0] cmp4_i276_reg_957;
wire   [0:0] cmp6_i279_fu_500_p2;
reg   [0:0] cmp6_i279_reg_967;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp8_fu_614_p2;
reg   [0:0] cmp8_reg_997;
wire   [7:0] pix_val_V_fu_628_p3;
reg   [7:0] pix_val_V_reg_1027;
reg   [10:0] barWidth_reg_1032;
wire   [9:0] add_ln214_fu_675_p2;
reg   [9:0] add_ln214_reg_1038;
wire   [10:0] add_ln1496_fu_701_p2;
reg   [10:0] add_ln1496_reg_1043;
wire   [16:0] sub40_i_fu_707_p2;
reg   [16:0] sub40_i_reg_1048;
wire   [7:0] outpix_val_V_68_fu_713_p3;
reg   [7:0] outpix_val_V_68_reg_1053;
wire   [16:0] add_ln1404_fu_720_p2;
reg   [16:0] add_ln1404_reg_1058;
wire   [7:0] select_ln1161_fu_726_p3;
reg   [7:0] select_ln1161_reg_1063;
wire   [7:0] select_ln1458_fu_733_p3;
reg   [7:0] select_ln1458_reg_1068;
wire   [7:0] select_ln1473_fu_740_p3;
reg   [7:0] select_ln1473_reg_1073;
reg   [15:0] y_1_reg_1078;
wire    ap_CS_fsm_state3;
reg   [7:0] outpix_val_V_load_reg_1086;
wire   [0:0] icmp_ln518_fu_754_p2;
reg   [7:0] outpix_val_V_1_load_reg_1091;
reg   [7:0] outpix_val_V_2_load_reg_1096;
reg   [7:0] outpix_val_V_3_load_reg_1101;
reg   [7:0] outpix_val_V_4_load_reg_1106;
reg   [7:0] outpix_val_V_5_load_reg_1111;
wire   [0:0] cmp59_not_fu_783_p2;
reg   [0:0] cmp59_not_reg_1116;
wire   [0:0] ult_fu_788_p2;
reg   [0:0] ult_reg_1121;
wire   [0:0] icmp_ln1404_fu_793_p2;
reg   [0:0] icmp_ln1404_reg_1126;
wire   [0:0] icmp_ln1404_1_fu_799_p2;
reg   [0:0] icmp_ln1404_1_reg_1131;
wire   [0:0] rev265_fu_825_p2;
reg   [0:0] rev265_reg_1136;
wire    ap_CS_fsm_state4;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_ready;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_srcYUV_read;
wire   [47:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_write;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_ap_vld;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [7:0] hBarSel_0_3_loc_0_fu_254;
reg   [7:0] hBarSel_1_3_loc_0_fu_250;
reg   [7:0] vBarSel_loc_0_fu_246;
reg   [7:0] hBarSel_0_loc_0_fu_242;
reg   [7:0] hBarSel_1_loc_0_fu_238;
reg   [7:0] vBarSel_1_loc_0_fu_234;
reg   [7:0] hBarSel_0_2_loc_0_fu_230;
reg   [7:0] hBarSel_1_2_loc_0_fu_226;
reg   [7:0] outpix_val_V_5_fu_218;
reg   [7:0] outpix_val_V_4_fu_214;
reg   [7:0] outpix_val_V_3_fu_210;
reg   [7:0] outpix_val_V_2_fu_206;
reg   [7:0] outpix_val_V_1_fu_202;
reg   [7:0] outpix_val_V_fu_198;
reg   [7:0] p_0_5_0_0_0253495_lcssa513_fu_194;
reg   [7:0] p_0_4_0_0_0251493_lcssa510_fu_190;
reg   [7:0] p_0_3_0_0_0249491_lcssa507_fu_186;
reg   [7:0] p_0_2_0_0_0247489_lcssa504_fu_182;
reg   [7:0] p_0_1_0_0_0245487_lcssa501_fu_178;
reg   [7:0] p_0_0_0_0_0243485_lcssa498_fu_174;
wire   [63:0] select_ln1162_fu_506_p3;
wire   [7:0] add_ln705_fu_813_p2;
reg   [15:0] y_fu_222;
wire   [15:0] add_ln518_fu_759_p2;
reg    ap_block_state1;
wire   [7:0] zext_ln518_fu_565_p1;
wire   [7:0] zext_ln1548_fu_557_p1;
wire   [7:0] zext_ln1530_fu_545_p1;
wire   [7:0] zext_ln1367_1_fu_537_p1;
wire   [7:0] zext_ln1367_fu_529_p1;
wire   [6:0] tmp_fu_478_p4;
wire   [13:0] trunc_ln1196_fu_639_p1;
wire   [13:0] add_ln1196_fu_643_p2;
wire   [13:0] add_ln1328_fu_659_p2;
wire   [9:0] trunc_ln1_fu_665_p4;
wire   [13:0] empty_fu_624_p1;
wire   [13:0] add_ln1329_fu_681_p2;
wire   [9:0] tmp_3_fu_687_p4;
wire   [10:0] zext_ln1496_fu_697_p1;
wire   [16:0] zext_ln1196_fu_635_p1;
wire   [16:0] loopHeight_cast17_fu_620_p1;
wire   [16:0] zext_ln518_1_fu_750_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 hBarSel_0_1 = 8'd0;
#0 hBarSel_1_1 = 8'd0;
#0 vBarSel = 3'd0;
#0 hBarSel_0 = 3'd0;
#0 hBarSel_1 = 3'd0;
#0 vBarSel_1 = 8'd0;
#0 hBarSel_0_2 = 3'd0;
#0 hBarSel_1_2 = 3'd0;
#0 rampStart = 8'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg = 1'b0;
end

exdes_v_tpg_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_address0),
    .ce0(blkYuv_ce0),
    .q0(blkYuv_q0)
);

exdes_v_tpg_0_tpgBackground_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_address0),
    .ce0(whiYuv_ce0),
    .q0(whiYuv_q0)
);

exdes_v_tpg_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_1_address0),
    .ce0(blkYuv_1_ce0),
    .q0(blkYuv_1_q0)
);

exdes_v_tpg_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_ready),
    .srcYUV_dout(srcYUV_dout),
    .srcYUV_num_data_valid(5'd0),
    .srcYUV_fifo_cap(5'd0),
    .srcYUV_empty_n(srcYUV_empty_n),
    .srcYUV_read(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_srcYUV_read),
    .ovrlayYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_din),
    .ovrlayYUV_num_data_valid(5'd0),
    .ovrlayYUV_fifo_cap(5'd0),
    .ovrlayYUV_full_n(ovrlayYUV_full_n),
    .ovrlayYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_write),
    .outpix_val_V_5(outpix_val_V_5_load_reg_1111),
    .outpix_val_V_4(outpix_val_V_4_load_reg_1106),
    .outpix_val_V_3(outpix_val_V_3_load_reg_1101),
    .outpix_val_V_2(outpix_val_V_2_load_reg_1096),
    .outpix_val_V_1(outpix_val_V_1_load_reg_1091),
    .outpix_val_V(outpix_val_V_load_reg_1086),
    .loopWidth(width),
    .pix_val_V(pix_val_V_reg_1027),
    .select_ln1161(select_ln1161_reg_1063),
    .cmp8(cmp8_reg_997),
    .bckgndId_load(bckgndId),
    .cmp6_i279(cmp6_i279_reg_967),
    .cmp4_i276(cmp4_i276_reg_957),
    .barWidth(barWidth_reg_1032),
    .zext_ln1328(barWidth_reg_1032),
    .barWidthMinSamples(add_ln214_reg_1038),
    .y(y_1_reg_1078),
    .ret_V_4(add_ln1496_reg_1043),
    .outpix_val_V_68(outpix_val_V_68_reg_1053),
    .select_ln1458(select_ln1458_reg_1068),
    .select_ln1473(select_ln1473_reg_1073),
    .sub40_i(sub40_i_reg_1048),
    .icmp_ln1404_1(icmp_ln1404_1_reg_1131),
    .icmp_ln1404(icmp_ln1404_reg_1126),
    .cmp35_i(icmp_reg_952),
    .passthruStartX_load(passthruStartX),
    .passthruEndX_load(passthruEndX),
    .cmp59_not(cmp59_not_reg_1116),
    .cmp68_not(rev265_reg_1136),
    .hBarSel_0_3_loc_1_out_i(hBarSel_0_3_loc_0_fu_254),
    .hBarSel_0_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o),
    .hBarSel_0_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o_ap_vld),
    .hBarSel_1_3_loc_1_out_i(hBarSel_1_3_loc_0_fu_250),
    .hBarSel_1_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o),
    .hBarSel_1_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_246),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_0_loc_1_out_i(hBarSel_0_loc_0_fu_242),
    .hBarSel_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o),
    .hBarSel_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o_ap_vld),
    .hBarSel_1_loc_1_out_i(hBarSel_1_loc_0_fu_238),
    .hBarSel_1_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o),
    .hBarSel_1_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o_ap_vld),
    .vBarSel_1_loc_1_out_i(vBarSel_1_loc_0_fu_234),
    .vBarSel_1_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o),
    .vBarSel_1_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o_ap_vld),
    .hBarSel_0_2_loc_1_out_i(hBarSel_0_2_loc_0_fu_230),
    .hBarSel_0_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o),
    .hBarSel_0_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o_ap_vld),
    .hBarSel_1_2_loc_1_out_i(hBarSel_1_2_loc_0_fu_226),
    .hBarSel_1_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o),
    .hBarSel_1_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o_ap_vld),
    .outpix_val_V_11_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out),
    .outpix_val_V_11_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out_ap_vld),
    .outpix_val_V_10_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out),
    .outpix_val_V_10_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out_ap_vld),
    .outpix_val_V_9_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out),
    .outpix_val_V_9_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out_ap_vld),
    .outpix_val_V_8_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out),
    .outpix_val_V_8_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out_ap_vld),
    .outpix_val_V_7_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out),
    .outpix_val_V_7_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out_ap_vld),
    .outpix_val_V_6_out(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out),
    .outpix_val_V_6_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out_ap_vld),
    .p_0_5_0_0_0253494_out_i(p_0_5_0_0_0253495_lcssa513_fu_194),
    .p_0_5_0_0_0253494_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o),
    .p_0_5_0_0_0253494_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o_ap_vld),
    .p_0_4_0_0_0251492_out_i(p_0_4_0_0_0251493_lcssa510_fu_190),
    .p_0_4_0_0_0251492_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o),
    .p_0_4_0_0_0251492_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o_ap_vld),
    .p_0_3_0_0_0249490_out_i(p_0_3_0_0_0249491_lcssa507_fu_186),
    .p_0_3_0_0_0249490_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o),
    .p_0_3_0_0_0249490_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o_ap_vld),
    .p_0_2_0_0_0247488_out_i(p_0_2_0_0_0247489_lcssa504_fu_182),
    .p_0_2_0_0_0247488_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o),
    .p_0_2_0_0_0247488_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o_ap_vld),
    .p_0_1_0_0_0245486_out_i(p_0_1_0_0_0245487_lcssa501_fu_178),
    .p_0_1_0_0_0245486_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o),
    .p_0_1_0_0_0245486_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o_ap_vld),
    .p_0_0_0_0_0243484_out_i(p_0_0_0_0_0243485_lcssa498_fu_174),
    .p_0_0_0_0_0243484_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o),
    .p_0_0_0_0_0243484_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o_ap_vld),
    .hBarSel_1_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1),
    .hBarSel_1_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1_ap_vld),
    .hBarSel_0_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1),
    .hBarSel_0_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1_ap_vld),
    .s(s),
    .hBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1),
    .hBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_ap_vld),
    .hBarSel_0(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0),
    .hBarSel_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_ap_vld),
    .hBarSel_1_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2),
    .hBarSel_1_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_ap_vld),
    .hBarSel_0_2(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2),
    .hBarSel_0_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_2_loc_0_fu_230 <= zext_ln1548_fu_557_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0_2_loc_0_fu_230 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_3_loc_0_fu_254 <= hBarSel_0_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0_3_loc_0_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_loc_0_fu_242 <= zext_ln1367_1_fu_537_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0_loc_0_fu_242 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_1_2_loc_0_fu_226 <= zext_ln518_fu_565_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1_2_loc_0_fu_226 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_1_3_loc_0_fu_250 <= hBarSel_1_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1_3_loc_0_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_1_loc_0_fu_238 <= zext_ln1530_fu_545_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1_loc_0_fu_238 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_1_loc_0_fu_234 <= vBarSel_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_1_loc_0_fu_234 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_246 <= zext_ln1367_fu_529_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_loc_0_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_222 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd0))) begin
        y_fu_222 <= add_ln518_fu_759_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln1404_reg_1058 <= add_ln1404_fu_720_p2;
        add_ln1496_reg_1043 <= add_ln1496_fu_701_p2;
        add_ln214_reg_1038 <= add_ln214_fu_675_p2;
        barWidth_reg_1032 <= {{add_ln1196_fu_643_p2[13:3]}};
        cmp8_reg_997 <= cmp8_fu_614_p2;
        outpix_val_V_68_reg_1053[6 : 0] <= outpix_val_V_68_fu_713_p3[6 : 0];
        pix_val_V_reg_1027[7] <= pix_val_V_fu_628_p3[7];
        select_ln1161_reg_1063 <= select_ln1161_fu_726_p3;
        select_ln1458_reg_1068 <= select_ln1458_fu_733_p3;
        select_ln1473_reg_1073 <= select_ln1473_fu_740_p3;
        sub40_i_reg_1048 <= sub40_i_fu_707_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmp4_i276_reg_957 <= cmp4_i276_fu_494_p2;
        cmp6_i279_reg_967 <= cmp6_i279_fu_500_p2;
        icmp_reg_952 <= icmp_fu_488_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd0))) begin
        cmp59_not_reg_1116 <= cmp59_not_fu_783_p2;
        icmp_ln1404_1_reg_1131 <= icmp_ln1404_1_fu_799_p2;
        icmp_ln1404_reg_1126 <= icmp_ln1404_fu_793_p2;
        outpix_val_V_1_load_reg_1091 <= outpix_val_V_1_fu_202;
        outpix_val_V_2_load_reg_1096 <= outpix_val_V_2_fu_206;
        outpix_val_V_3_load_reg_1101 <= outpix_val_V_3_fu_210;
        outpix_val_V_4_load_reg_1106 <= outpix_val_V_4_fu_214;
        outpix_val_V_5_load_reg_1111 <= outpix_val_V_5_fu_218;
        outpix_val_V_load_reg_1086 <= outpix_val_V_fu_198;
        ult_reg_1121 <= ult_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_0_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_0_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        hBarSel_1_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_hBarSel_1_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_1_fu_202 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_2_fu_206 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_3_fu_210 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_4_fu_214 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_10_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_5_fu_218 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_11_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        outpix_val_V_fu_198 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_outpix_val_V_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_0_0_0_0243485_lcssa498_fu_174 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_0_0_0_0243484_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_1_0_0_0245487_lcssa501_fu_178 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_1_0_0_0245486_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_2_0_0_0247489_lcssa504_fu_182 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_2_0_0_0247488_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_3_0_0_0249491_lcssa507_fu_186 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_3_0_0_0249490_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_4_0_0_0251493_lcssa510_fu_190 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_4_0_0_0251492_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_5_0_0_0253495_lcssa513_fu_194 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_p_0_5_0_0_0253494_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd1))) begin
        rampStart <= add_ln705_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rev265_reg_1136 <= rev265_fu_825_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_1_reg_1078 <= y_fu_222;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        blkYuv_1_ce0 = 1'b1;
    end else begin
        blkYuv_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        blkYuv_ce0 = 1'b1;
    end else begin
        blkYuv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ovrlayYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_write;
    end else begin
        ovrlayYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        srcYUV_read = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_srcYUV_read;
    end else begin
        srcYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        whiYuv_ce0 = 1'b1;
    end else begin
        whiYuv_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln518_fu_754_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1196_fu_643_p2 = (trunc_ln1196_fu_639_p1 + 14'd7);

assign add_ln1328_fu_659_p2 = (trunc_ln1196_fu_639_p1 + 14'd15);

assign add_ln1329_fu_681_p2 = (empty_fu_624_p1 + 14'd15);

assign add_ln1404_fu_720_p2 = ($signed(loopHeight_cast17_fu_620_p1) + $signed(17'd131071));

assign add_ln1496_fu_701_p2 = ($signed(zext_ln1496_fu_697_p1) + $signed(11'd2047));

assign add_ln214_fu_675_p2 = ($signed(trunc_ln1_fu_665_p4) + $signed(10'd1022));

assign add_ln518_fu_759_p2 = (y_fu_222 + 16'd1);

assign add_ln705_fu_813_p2 = (motionSpeed + rampStart);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign blkYuv_1_address0 = select_ln1162_fu_506_p3;

assign blkYuv_address0 = select_ln1162_fu_506_p3;

assign cmp4_i276_fu_494_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign cmp59_not_fu_783_p2 = ((y_fu_222 < passthruStartY) ? 1'b1 : 1'b0);

assign cmp6_i279_fu_500_p2 = ((colorFormat == 8'd1) ? 1'b1 : 1'b0);

assign cmp8_fu_614_p2 = ((enableInput != 8'd0) ? 1'b1 : 1'b0);

assign empty_fu_624_p1 = height[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ap_start_reg;

assign icmp_fu_488_p2 = ((tmp_fu_478_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1404_1_fu_799_p2 = ((add_ln1404_reg_1058 == zext_ln518_1_fu_750_p1) ? 1'b1 : 1'b0);

assign icmp_ln1404_fu_793_p2 = ((y_fu_222 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln518_fu_754_p2 = ((y_fu_222 == height) ? 1'b1 : 1'b0);

assign loopHeight_cast17_fu_620_p1 = height;

assign outpix_val_V_68_fu_713_p3 = ((cmp4_i276_reg_957[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign ovrlayYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_357_ovrlayYUV_din;

assign pix_val_V_fu_628_p3 = ((cmp4_i276_reg_957[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign rev265_fu_825_p2 = (ult_reg_1121 ^ 1'd1);

assign select_ln1161_fu_726_p3 = ((cmp4_i276_reg_957[0:0] == 1'b1) ? 8'd0 : blkYuv_q0);

assign select_ln1162_fu_506_p3 = ((cmp6_i279_fu_500_p2[0:0] == 1'b1) ? 64'd1 : 64'd2);

assign select_ln1458_fu_733_p3 = ((cmp4_i276_reg_957[0:0] == 1'b1) ? 8'd255 : whiYuv_q0);

assign select_ln1473_fu_740_p3 = ((cmp4_i276_reg_957[0:0] == 1'b1) ? 8'd0 : blkYuv_1_q0);

assign start_out = real_start;

assign sub40_i_fu_707_p2 = ($signed(zext_ln1196_fu_635_p1) + $signed(17'd131071));

assign tmp_3_fu_687_p4 = {{add_ln1329_fu_681_p2[13:4]}};

assign tmp_fu_478_p4 = {{colorFormat[7:1]}};

assign trunc_ln1196_fu_639_p1 = width[13:0];

assign trunc_ln1_fu_665_p4 = {{add_ln1328_fu_659_p2[13:4]}};

assign ult_fu_788_p2 = ((y_fu_222 < passthruEndY) ? 1'b1 : 1'b0);

assign whiYuv_address0 = select_ln1162_fu_506_p3;

assign zext_ln1196_fu_635_p1 = width;

assign zext_ln1367_1_fu_537_p1 = hBarSel_0;

assign zext_ln1367_fu_529_p1 = vBarSel;

assign zext_ln1496_fu_697_p1 = tmp_3_fu_687_p4;

assign zext_ln1530_fu_545_p1 = hBarSel_1;

assign zext_ln1548_fu_557_p1 = hBarSel_0_2;

assign zext_ln518_1_fu_750_p1 = y_fu_222;

assign zext_ln518_fu_565_p1 = hBarSel_1_2;

always @ (posedge ap_clk) begin
    pix_val_V_reg_1027[6:0] <= 7'b0000000;
    outpix_val_V_68_reg_1053[7] <= 1'b1;
end

endmodule //exdes_v_tpg_0_tpgBackground
